#!/usr/bin/env python3.7

from PyQt5.QtGui import * 
from PyQt5.QtWidgets import * 
import threading, os, sys

print( '''
|
|   DPST fixer
|   _____________________
|   
|   creates systray icon and changes 
|   to very similar (to forse screen refresh) 
|   every 0.25 seconds
|
|   (c) cjayho, 2021+
|
|   This software is distributed under the terms
|   of 3-clause BSD license.
|
''')

os.chdir(os.path.dirname(sys.argv[0]))

app = QApplication([]) 
app.setQuitOnLastWindowClosed(False) 
  
# Adding an icon 
icon1 = QIcon("icon1.png") 
icon2 = QIcon("icon2.png") 
i = True
ii = False

tray = QSystemTrayIcon() 
tray.setVisible(True) 

def changeIcon():

    global i, ii
    
    if ii == True:
        return

    threading.Timer( 0.25, changeIcon ).start()
    
    if i == True:
        tray.setIcon(icon1)
        i = False
    else:
        tray.setIcon(icon2)
        i = True

def qq():
    global ii, app
    ii = True
    app.quit()

def abt():
	msgbox = QMessageBox();
	msgbox.setIcon(QMessageBox.Information)
	msgbox.setWindowTitle("About DPST fixer")
	msgbox.setText("DPST fixer")
	msgbox.setInformativeText('''© cjayho, 2021+

https://github.com/cjayho/dpst-fixer

This software is distributed under the 
terms of 3-clause BSD license.
''');
	msgbox.setWindowIcon(icon1);
	msgbox.exec();

menu = QMenu() 
  
quit = QAction("Quit") 
quit.triggered.connect(qq) 
about = QAction("About...")
about.triggered.connect(abt)

menu.addAction(about)
menu.addSeparator()
menu.addAction(quit)

tray.setContextMenu(menu)
tray.setToolTip( "DPST fixer" )

changeIcon()

app.exec_() 
